# Form implementation generated from reading ui file 'c:\Users\Dimitry\ДМиТИ\long_arithmetic\UI\second_choice.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class InputForm1(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_1 = QtWidgets.QLabel(Form)
        self.label_1.setText("Введите первое число")
        self.number_1 = QtWidgets.QLineEdit(Form)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setText("Введите второе число")
        self.number_2 = QtWidgets.QLineEdit(Form)
        self.verticalLayout.addWidget(self.label_1)
        self.verticalLayout.addWidget(self.number_1)
        self.verticalLayout.addWidget(self.label_2)
        self.verticalLayout.addWidget(self.number_2)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


class InputForm2(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_1 = QtWidgets.QLabel(Form)
        self.label_1.setText("Введите число")
        self.number_1 = QtWidgets.QLineEdit(Form)
        self.verticalLayout.addWidget(self.label_1)
        self.verticalLayout.addWidget(self.number_1)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


class InputForm3(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_1 = QtWidgets.QLabel(Form)
        self.label_1.setText("Введите число")
        self.number_1 = QtWidgets.QLineEdit(Form)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setText("Введите цифру (от 0 до 9)")
        self.digit_1 = QtWidgets.QSpinBox(Form)
        self.verticalLayout.addWidget(self.label_1)
        self.verticalLayout.addWidget(self.number_1)
        self.verticalLayout.addWidget(self.label_2)
        self.verticalLayout.addWidget(self.digit_1)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


class InputForm4(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_1 = QtWidgets.QLabel(Form)
        self.label_1.setText("Введите первое число")
        self.number_1 = QtWidgets.QLineEdit(Form)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setText("Введите второе число")
        self.number_2 = QtWidgets.QLineEdit(Form)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setText("Введите цифру (от 0 до 9)")
        self.digit_2 = QtWidgets.QSpinBox(Form)
        self.verticalLayout.addWidget(self.label_1)
        self.verticalLayout.addWidget(self.number_1)
        self.verticalLayout.addWidget(self.label_2)
        self.verticalLayout.addWidget(self.number_2)
        self.verticalLayout.addWidget(self.label_3)
        self.verticalLayout.addWidget(self.digit_2)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))