# Form implementation generated from reading ui file 'c:\Users\Dimitry\ДМиТИ\long_arithmetic\UI\second_choice.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class InputForm1(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.number_1 = QtWidgets.QLineEdit(Form)
        self.number_2 = QtWidgets.QLineEdit(Form)
        self.verticalLayout.addWidget(self.number_1)
        self.verticalLayout.addWidget(self.number_2)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


class InputForm2(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.number_1 = QtWidgets.QLineEdit(Form)
        self.verticalLayout.addWidget(self.number_1)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


class InputForm3(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.number_1 = QtWidgets.QLineEdit(Form)
        self.digit_1 = QtWidgets.QSpinBox(Form)
        self.verticalLayout.addWidget(self.number_1)
        self.verticalLayout.addWidget(self.digit_1)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


class InputForm4(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.number_1 = QtWidgets.QLineEdit(Form)
        self.number_2 = QtWidgets.QLineEdit(Form)
        self.digit_2 = QtWidgets.QSpinBox(Form)
        self.verticalLayout.addWidget(self.number_1)
        self.verticalLayout.addWidget(self.number_2)
        self.verticalLayout.addWidget(self.digit_2)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


class InputForm5(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.numerator_1 = QtWidgets.QLineEdit(Form)
        self.denominator_1 = QtWidgets.QLineEdit(Form)
        self.verticalLayout.addWidget(self.numerator_1)
        self.verticalLayout.addWidget(self.denominator_1)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


class InputForm6(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.verticalLayout1 = QtWidgets.QVBoxLayout()
        self.verticalLayout1.setObjectName("verticalLayout1")

        self.verticalLayout2 = QtWidgets.QVBoxLayout()
        self.verticalLayout2.setObjectName("verticalLayout")

        self.numerator_1 = QtWidgets.QLineEdit(Form)
        self.denominator_1 = QtWidgets.QLineEdit(Form)
        self.verticalLayout1.addWidget(self.numerator_1)
        self.verticalLayout1.addWidget(self.denominator_1)
        self.numerator_2 = QtWidgets.QLineEdit(Form)
        self.denominator_2 = QtWidgets.QLineEdit(Form)
        self.verticalLayout2.addWidget(self.numerator_2)
        self.verticalLayout2.addWidget(self.denominator_2)

        self.horizontalLayout.addLayout(self.verticalLayout1)
        self.horizontalLayout.addLayout(self.verticalLayout2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))



class InputForm7(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.verticalLayout1 = QtWidgets.QVBoxLayout()
        self.verticalLayout1.setObjectName("verticalLayout1")

        self.verticalLayout2 = QtWidgets.QVBoxLayout()
        self.verticalLayout2.setObjectName("verticalLayout")

        self.numerator_1 = QtWidgets.QLineEdit(Form)
        self.denominator_1 = QtWidgets.QLineEdit(Form)
        self.verticalLayout1.addWidget(self.numerator_1)
        self.verticalLayout1.addWidget(self.denominator_1)
        self.numerator_2 = QtWidgets.QLineEdit(Form)
        self.denominator_2 = QtWidgets.QLineEdit(Form)
        self.verticalLayout2.addWidget(self.numerator_2)
        self.verticalLayout2.addWidget(self.denominator_2)

        self.horizontalLayout.addLayout(self.verticalLayout1)
        self.horizontalLayout.addLayout(self.verticalLayout2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


class InputForm8(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.verticalLayout1 = QtWidgets.QVBoxLayout()
        self.verticalLayout1.setObjectName("verticalLayout1")

        self.verticalLayout2 = QtWidgets.QVBoxLayout()
        self.verticalLayout2.setObjectName("verticalLayout")

        self.numerator_1 = QtWidgets.QLineEdit(Form)
        self.denominator_1 = QtWidgets.QLineEdit(Form)
        self.verticalLayout1.addWidget(self.numerator_1)
        self.verticalLayout1.addWidget(self.denominator_1)
        self.numerator_2 = QtWidgets.QLineEdit(Form)
        self.denominator_2 = QtWidgets.QLineEdit(Form)
        self.verticalLayout2.addWidget(self.numerator_2)
        self.verticalLayout2.addWidget(self.denominator_2)

        self.horizontalLayout.addLayout(self.verticalLayout1)
        self.horizontalLayout.addLayout(self.verticalLayout2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


class InputForm9(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.verticalLayout1 = QtWidgets.QVBoxLayout()
        self.verticalLayout1.setObjectName("verticalLayout1")

        self.verticalLayout2 = QtWidgets.QVBoxLayout()
        self.verticalLayout2.setObjectName("verticalLayout")

        self.numerator_1 = QtWidgets.QLineEdit(Form)
        self.denominator_1 = QtWidgets.QLineEdit(Form)
        self.verticalLayout1.addWidget(self.numerator_1)
        self.verticalLayout1.addWidget(self.denominator_1)
        self.numerator_2 = QtWidgets.QLineEdit(Form)
        self.denominator_2 = QtWidgets.QLineEdit(Form)
        self.verticalLayout2.addWidget(self.numerator_2)
        self.verticalLayout2.addWidget(self.denominator_2)

        self.horizontalLayout.addLayout(self.verticalLayout1)
        self.horizontalLayout.addLayout(self.verticalLayout2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))

    
class InputForm10(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)

        self.degree = QtWidgets.QSpinBox(Form)
        self.degree.valueChanged.connect(self.input_regenerator)

        self.horizontalLayout = QtWidgets.QVBoxLayout()
        self.polynomial = [PolynomialElement(parent=Form) for _ in range(5)]
        [self.horizontalLayout.addWidget(widget) for widget in self.polynomial]
        self.verticalLayout.addWidget(self.degree)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def input_regenerator(self):
        print(123)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


class PolynomialElement(QtWidgets.QWidget):
    def __init__(self, parent=None) -> None:
        super().__init__(parent=parent)
        self.one_rational = QtWidgets.QVBoxLayout()
        self.numerator_1 = QtWidgets.QLineEdit()
        self.denominator_1 = QtWidgets.QLineEdit()
        self.one_rational.addWidget(self.numerator_1)
        self.one_rational.addWidget(self.denominator_1)