# Form implementation generated from reading ui file 'c:\Users\Dimitry\ДМиТИ\long_arithmetic\UI\second_choice.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class InputForm1(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.number_1 = QtWidgets.QLineEdit(Form)
        self.number_2 = QtWidgets.QLineEdit(Form)
        self.verticalLayout.addWidget(self.number_1)
        self.verticalLayout.addWidget(self.number_2)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


class InputForm2(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.number_1 = QtWidgets.QLineEdit(Form)
        self.verticalLayout.addWidget(self.number_1)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


class InputForm3(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.number_1 = QtWidgets.QLineEdit(Form)
        self.digit_1 = QtWidgets.QSpinBox(Form)
        self.verticalLayout.addWidget(self.number_1)
        self.verticalLayout.addWidget(self.digit_1)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


class InputForm4(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.number_1 = QtWidgets.QLineEdit(Form)
        self.number_2 = QtWidgets.QLineEdit(Form)
        self.digit_2 = QtWidgets.QSpinBox(Form)
        self.verticalLayout.addWidget(self.number_1)
        self.verticalLayout.addWidget(self.number_2)
        self.verticalLayout.addWidget(self.digit_2)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


class InputForm5(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.numerator_1 = QtWidgets.QLineEdit(Form)
        self.denominator_1 = QtWidgets.QLineEdit(Form)
        self.verticalLayout.addWidget(self.numerator_1)
        self.verticalLayout.addWidget(self.denominator_1)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


class InputForm6(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.numerator_1 = QtWidgets.QLineEdit(Form)
        self.denominator_1 = QtWidgets.QLineEdit(Form)
        self.verticalLayout.addWidget(self.numerator_1)
        self.verticalLayout.addWidget(self.denominator_1)
        self.numerator_2 = QtWidgets.QLineEdit(Form)
        self.denominator_2 = QtWidgets.QLineEdit(Form)
        self.verticalLayout.addWidget(self.numerator_2)
        self.verticalLayout.addWidget(self.denominator_2)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))